#Ricos pelo Acaso

Link para o vídeo: https://youtu.be/e_ZRDG4F4ZA

também tem um acesso ao fundamentus no MINHA VERSAO 15

# Importando Bibliotecas

In [1]:
import numpy as np
import pandas as pd
import string
import warnings
import requests
warnings.filterwarnings('ignore')

# Obtendo e tratando os dados

In [2]:
#url = 'https://www.fundamentus.com.br/resultado.php'
#df = pd.read_html(url, decimal=',', thousands='.')[0]
#A url que você quer acesssar
#url = "https://www.portalbrasil.net/igpm.htm"
url = 'https://www.fundamentus.com.br/resultado.php'

#Informações para fingir ser um navegador
header = {
  "User-Agent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.75 Safari/537.36",
  "X-Requested-With": "XMLHttpRequest"
}
#juntamos tudo com a requests
r = requests.get(url, headers=header)
#E finalmente usamos a função read_html do pandas
lista = pd.read_html(r.text)
print(lista)
df = pd.concat(lista)
type(df)
df.head()

[      Papel  Cotação          P/L         P/VP      PSR Div.Yield  P/Ativo  \
0     VSPT4      0.0      0.00000      0.00000      0.0     0,00%        0
1     VSPT3      0.0      0.00000      0.00000      0.0     0,00%        0
2     VNET3      0.0      0.00000      0.00000      0.0     0,00%        0
3     CFLU4      1.0      0.00000      0.00000      0.0     0,00%        0
4     CLAN3      0.0      0.00000      0.00000      0.0     0,00%        0
5     CLSC6      0.0      0.00000      0.00000      0.0     0,00%        0
6     CSTB3  15000.0      0.00000      0.00000      0.0     0,00%        0
7     CSTB4  14769.0      0.00000      0.00000      0.0     0,00%        0
8     IVTT3      0.0      0.00000      0.00000      0.0     0,00%        0
9     MNSA3     42.0      0.00000      0.00000      0.0     0,00%        0
10    MNSA4     47.0      0.00000      0.00000      0.0     0,00%        0
11    ODER3      0.0      0.00000      0.00000      0.0     0,00%        0
12    ODER4      0.0      0.00000      0.00000      0.0     0,00%        0
13    PMET3      0.0      0.00000      0.00000      0.0     0,00%        0
14    POPR4   1017.0      0.00000      0.00000      0.0     0,00%        0
15    PORP4    240.0      0.00000      0.00000      0.0     0,00%        0
16   BBTG12    315.0     -1.74991      0.00000      0.0     0,00%        0
17    CVCB3   1675.0 -74152.00000    376.00000   1693.0     2,15%      420
18    STBP3    422.0 -62424.00000    213.00000   3042.0     0,41%      868
19    PLDN4  48600.0 -55307.00000    108.00000    919.0     0,00%      611
20   STBP11   1440.0 -42602.00000    146.00000   2076.0     0,00%      593
21    LCSA4   3509.0 -33752.00000 -22800.00000  79738.0     0,00%   125308
22    BHGR3   1910.0 -27216.00000    110.00000   3613.0     0,00%      855
23    MAPT3   5001.0 -26113.00000   -806.00000      0.0     0,00%    59456
24    GFSA3    456.0 -24298.00000     76.00000   2472.0     0,00%      316
25    BTOW3   9541.0 -22819.00000    959.00000   6562.0     0,00%     3247
26    RJCP3      1.0 -22470.00000     65.00000      0.0     0,00%      619
27    MAPT4   4141.0 -21623.00000   -667.00000      0.0     0,00%    49231
28    ABYA3    491.0 -21480.00000    176.00000   2055.0     0,00%      527
29    PITI4    128.0 -20474.00000      0.00000      0.0     0,00%        0
..      ...      ...          ...          ...      ...       ...      ...
873   TMAR5   4267.0  11435.00000     72.00000    527.0     0,00%      184
874   FLCL6    991.0  11565.00000   6125.00000  11283.0     0,00%    11168
875   ROMI4  18500.0  11759.00000   1437.00000  13863.0     0,00%     7570
876   ARZZ3   5454.0  11806.00000    741.00000   3449.0     0,65%     2866
877   NETC3   3850.0  12310.00000    212.00000   1290.0     0,00%     1074
878   NETC4   4000.0  12789.00000    220.00000   1340.0     0,00%     1116
879   UGPA4   2710.0  12958.00000    331.00000    359.0     0,00%      886
880   FLCL3   1150.0  13420.00000   7108.00000  13094.0     0,00%    12959
881   FLCL5   1250.0  14587.00000   7726.00000  14232.0     0,00%    14086
882   MOVI3   1760.0  16143.00000    241.00000   1275.0     1,67%      705
883   TMAR3   6200.0  16616.00000    104.00000    765.0     0,00%      268
884   VULC4   1800.0  21567.00000    430.00000   4132.0     0,00%     2949
885   JBSS3   2160.0  24160.00000    160.00000    247.0     2,56%      355
886   OMGE3   3746.0  29508.00000      2.65446   8967.0     0,00%   945969
887   NORD3    543.0  29712.00000    -26.00000  22697.0     0,00%     2115
888   ELEV3   2430.0  31239.00000    322.00000    688.0     0,00%      954
889   PRBC4   1454.0  32225.00000   4063.00000      0.0     0,00%        0
890   RHDS4    100.0  36345.00000   2950.00000   4977.0     0,00%     7182
891   MGLU3   9063.0  39866.00000   1978.00000   6677.0     0,22%     7162
892   ARTR3   1001.0  42157.00000     90.00000   1232.0     0,00%      359
893   LWSA3   5715.0  45281.00000   1116.00000  16773.0     0,00%     6072
894   GUAR4  15100.0  45774.00000   1536.00000  11028.0     0,00%     6232
895   BIDI3   1708.0  53718.00000    617.00000      0.0     0,50%        0
896  BIDI11   5321.0  55783.00000    641.00000      0.0     0,48%        0
897   BIDI4   1783.0  56077.00000    644.00000      0.0     0,48%        0
898   UBBR4    749.0  61027.00000    199.00000      0.0     0,00%        0
899   SQIA3   2235.0  67097.00000    365.00000   8185.0     0,00%     2602
900  UBBR11   1475.0      1.20181    391.00000      0.0     0,00%        0
901   UBBR3   1800.0      1.46661    477.00000      0.0     0,00%        0
902   LINX3   3466.0      2.20595    391.00000   7809.0     0,32%     2643

     P/Cap.Giro       P/EBIT  P/Ativ Circ.Liq      ...       EV/EBITDA  \
0        0.0000      0.00000          0.00000      ...             0.0
1        0.0000      0.00000          0.00000      ...             0.0
2        0.0000      0.00000          0.00000      ...             0.0
3        0.0000      0.00000          0.00000      ...             0.0
4        0.0000      0.00000          0.00000      ...             0.0
5        0.0000      0.00000          0.00000      ...             0.0
6        0.0000      0.00000          0.00000      ...             0.0
7        0.0000      0.00000          0.00000      ...             0.0
8        0.0000      0.00000          0.00000      ...             0.0
9        0.0000      0.00000          0.00000      ...             0.0
10       0.0000      0.00000          0.00000      ...             0.0
11       0.0000      0.00000          0.00000      ...             0.0
12       0.0000      0.00000          0.00000      ...             0.0
13       0.0000      0.00000          0.00000      ...             0.0
14       0.0000      0.00000          0.00000      ...             0.0
15       0.0000      0.00000          0.00000      ...             0.0
16       0.0000      0.00000          0.00000      ...             0.0
17     -53.8483    640.00000       -179.00000      ...           721.0
18    1024.0000   7461.00000       -203.00000      ...          1619.0
19     107.0000  -7556.00000        310.00000      ...         -3312.0
20     699.0000   5092.00000       -138.00000      ...          1119.0
21  -20227.0000 -50580.00000      -9661.00000      ...        -50656.0
22  -19445.0000   2370.00000       -856.00000      ...          1420.0
23       0.0000 -29844.00000          0.00000      ...        -29844.0
24     100.0000   2297.00000        216.00000      ...          2050.0
25    1049.0000  23157.00000      -4537.00000      ...          6732.0
26       0.0000 -52294.00000          0.00000      ...        -91732.0
27       0.0000 -24712.00000          0.00000      ...        -24712.0
28     198.0000   1996.00000       -275.00000      ...          3367.0
29       0.0000     -2.63765          0.00000      ...         11107.0
..          ...          ...              ...      ...             ...
873    151.0000    410.00000        -51.00000      ...           324.0
874  14305.0000   6497.00000      -2775.00000      ...          6711.0
875   2995.0000  19247.00000       7549.00000      ...         12571.0
876    709.0000  25326.00000       2301.00000      ...          4863.0
877  -3302.0000   1082.00000       -296.00000      ...           527.0
878  -3431.0000   1124.00000       -308.00000      ...           545.0
879    330.0000   1889.00000       -338.00000      ...          1533.0
880  16600.0000   7540.00000      -3221.00000      ...          7754.0
881  18044.0000   8195.00000      -3501.00000      ...          8409.0
882   1180.0000   1020.00000       -198.00000      ...           814.0
883    220.0000    596.00000        -74.00000      ...           396.0
884    620.0000   6526.00000        932.00000      ...          2905.0
885    207.0000    308.00000        -96.00000      ...           438.0
886     12.4459   2521.00000         -1.85351      ...          1819.0
887    -75.0000  -5626.00000        -23.00000      ...        -11428.0
888    575.0000   3719.00000       -518.00000      ...          5141.0
889      0.0000      0.00000          0.00000      ...             0.0
890 -59356.0000   6811.00000      -2455.00000      ...          5372.0
891   3970.0000  24297.00000      89799.00000      ...         11775.0
892  -1275.0000    938.00000        -70.00000      ...           639.0
893   1506.0000  16955.00000       2334.00000      ...          6952.0
894   4309.0000      1.16738     -18507.00000      ...         13424.0
895      0.0000      0.00000          0.00000      ...             0.0
896      0.0000      0.00000          0.00000      ...             0.0
897      0.0000      0.00000          0.00000      ...             0.0
898      0.0000      0.00000          0.00000      ...             0.0
899    516.0000  64995.00000        815.00000      ...          6085.0
900      0.0000      0.00000          0.00000      ...             0.0
901      0.0000      0.00000          0.00000      ...             0.0
902   1150.0000   4399.00000       3181.00000      ...          2172.0

     Mrg Ebit Mrg. Líq. Liq. Corr.       ROIC      ROE       Liq.2meses  \
0       0,00%     0,00%          0      0,00%   -2,62%              000
1       0,00%     0,00%          0      0,00%   -2,62%              000
2       0,00%     0,00%          0      0,00%    7,61%              000
3       8,88%    10,72%        110     17,68%   32,15%              000
4       0,00%     0,00%          0      0,00%   -1,05%              000
5       0,00%     0,00%          0      0,00%   22,90%              000
6      40,85%    28,98%        260     22,40%   20,11%              000
7      40,85%    28,98%        260     22,40%   20,11%              000
8       0,00%     0,00%          0      0,00%   -0,40%              000
9    -208,15%  -362,66%        363    -13,50%  145,70%              000
10   -208,15%  -362,66%        363    -13,50%  145,70%              000
11      0,00%     0,00%          0      0,00%   17,07%              000
12      0,00%     0,00%          0      0,00%   17,07%              000
13      0,00%     0,00%          0      0,00%    4,10%              000
14      8,66%     5,65%        108     15,25%   19,93%              000
15      0,00%     0,00%          0      0,00%   -2,08%              000
16      0,00%     0,00%          0      0,00%    0,00%              000
17     26,47%    -0,11%        100      8,21%   -0,51%     78.703.10000
18      4,08%    -0,49%        206      1,33%   -0,34%     18.930.80000
19     -1,22%    -0,17%       1081     -1,27%   -0,20%              000
20      4,08%    -0,49%        206      1,33%   -0,34%              000
21    -15,77%   -23,63%         29    -28,74%   67,55%              000
22     15,24%    -1,31%         96      3,93%   -0,40%              000
23      0,00%     0,00%          0      0,00%    3,09%            11366
24     10,76%    -1,15%        176      1,83%   -0,31%     33.682.10000
25      2,83%    -2,88%        210      3,37%   -4,20%    357.128.00000
26      0,00%     0,00%          0      0,00%   -0,29%              000
27      0,00%     0,00%          0      0,00%    3,09%         84.98740
28     10,29%    -0,96%        209      2,78%   -0,82%              000
29      0,00%     0,00%          0      0,00%    0,00%              000
..        ...       ...        ...        ...      ...              ...
873    12,84%    -0,42%        162      5,78%    0,63%              000
874    17,37%     9,76%        123     22,91%   52,97%              000
875     7,20%    11,82%        179      4,54%   12,22%              000
876     1,36%     2,92%        221      1,89%    6,28%     33.953.30000
877    11,93%     1,55%         80     10,95%    1,72%              000
878    11,93%     1,55%         80     10,95%    1,72%              000
879     1,90%     0,31%        241      6,51%    2,56%              000
880    17,37%     9,76%        123     22,91%   52,97%              000
881    17,37%     9,76%        123     22,91%   52,97%              000
882    12,50%     0,79%        120     11,42%    1,50%     48.332.70000
883    12,84%    -0,42%        162      5,78%    0,63%              000
884     6,33%     1,91%        408      5,92%    1,99%              000
885     8,00%     0,18%        180     15,57%    0,66%    391.706.00000
886    35,57%     3,63%        247  4.178,63%  899,57%     40.115.70000
887   -40,34%     7,64%          2     -3,85%   -0,09%          4.19120
888     1,85%     0,27%        147      3,01%    1,03%              000
889     0,00%     0,00%          0      0,00%   12,61%              000
890     7,31%     1,17%         97     11,80%    8,12%              000
891     2,75%     1,67%        139      4,95%    4,96%  1.073.540.00000
892    13,14%     0,29%         76      4,13%    0,21%              000
893     9,89%     3,70%        229      7,03%    2,46%    107.739.00000
894     0,94%     2,41%        135      0,67%    3,36%              000
895     0,00%     0,00%          0      0,00%    1,15%      7.572.42000
896     0,00%     0,00%          0      0,00%    1,15%     60.728.90000
897     0,00%     0,00%          0      0,00%    1,15%     47.190.20000
898     0,00%     0,00%          0      0,00%    0,33%              000
899     1,26%     1,23%        596      0,91%    0,54%     21.554.10000
900     0,00%     0,00%          0      0,00%    0,33%              000
901     0,00%     0,00%          0      0,00%    0,33%              000
902    17,75%     0,35%        230      8,11%    0,18%    120.253.00000

          Patrim. Líq Dív.Brut/ Patrim.  Cresc. Rec.5a
0     4.736.050.00000               0.0        438,95%
1     4.736.050.00000               0.0        438,95%
2     9.145.920.00000               0.0         -5,18%
3        60.351.00000               6.0          8,14%
4     1.012.240.00000               0.0        -63,96%
5     1.611.840.00000               0.0          7,54%
6     8.420.670.00000              14.0         31,91%
7     8.420.670.00000              14.0         31,91%
8     1.083.050.00000               0.0         20,67%
9        -9.105.00000            -652.0        -41,11%
10       -9.105.00000            -652.0        -41,11%
11      220.989.00000               0.0          5,60%
12      220.989.00000               0.0          5,60%
13     -290.863.00000               0.0         37,74%
14      545.803.00000              82.0         30,93%
15       22.399.00000               0.0         13,66%
16                000               0.0          0,00%
17      770.701.00000             238.0         19,58%
18    1.324.970.00000              33.0          3,60%
19      289.939.00000               1.0         10,26%
20    1.324.970.00000              33.0          3,60%
21     -377.568.00000             -35.0      6.354,07%
22    1.077.600.00000              20.0         20,67%
23       -5.702.00000               0.0          0,00%
24    1.175.850.00000              57.0        -24,38%
25    5.570.280.00000             122.0         -3,60%
26       17.287.20000               0.0          0,00%
27       -5.702.00000               0.0          0,00%
28      292.060.00000             131.0         16,41%
29                000               0.0        -29,63%
..                ...               ...            ...
873  20.448.500.00000             138.0         14,80%
874      72.920.00000             296.0        -29,63%
875     809.051.00000              53.0          7,29%
876     669.467.00000              90.0          6,59%
877   6.812.390.00000              28.0         66,63%
878   6.812.390.00000              28.0         66,63%
879   9.116.420.00000             214.0          3,02%
880      72.920.00000             296.0        -29,63%
881      72.920.00000             296.0        -29,63%
882   2.179.270.00000             171.0         25,29%
883  20.448.500.00000             138.0         14,80%
884   1.029.360.00000              27.0          1,43%
885  36.011.800.00000             214.0          7,39%
886       2.731.86000             161.0         58,17%
887    -139.667.00000             -27.0         74,97%
888     489.356.00000             135.0          3,69%
889   1.165.810.00000               0.0         12,27%
890     272.045.00000             149.0          4,38%
891   7.443.840.00000              22.0         25,27%
892   6.427.780.00000             128.0          0,22%
893     644.643.00000              30.0          0,00%
894   4.906.450.00000              81.0          5,46%
895   2.115.160.00000               0.0         15,58%
896   2.115.160.00000               0.0         15,58%
897   2.115.160.00000               0.0         15,58%
898  10.317.200.00000               0.0         10,58%
899     432.572.00000              18.0         24,13%
900  10.317.200.00000               0.0         10,58%
901  10.317.200.00000               0.0         10,58%
902   1.679.890.00000              19.0         15,75%

[903 rows x 21 columns]]

,Papel,Cotação,P/L,P/VP,PSR,Div.Yield,P/Ativo,P/Cap.Giro,P/EBIT,P/Ativ Circ.Liq,...,EV/EBITDA,Mrg Ebit,Mrg. Líq.,Liq. Corr.,ROIC,ROE,Liq.2meses,Patrim. Líq,Dív.Brut/ Patrim.,Cresc. Rec.5a
0,VSPT4,0.0,0.0,0.0,0.0,"0,00%",0,0.0,0.0,0.0,...,0.0,"0,00%","0,00%",0,"0,00%","-2,62%",000,4.736.050.00000,0.0,"438,95%"
1,VSPT3,0.0,0.0,0.0,0.0,"0,00%",0,0.0,0.0,0.0,...,0.0,"0,00%","0,00%",0,"0,00%","-2,62%",000,4.736.050.00000,0.0,"438,95%"
2,VNET3,0.0,0.0,0.0,0.0,"0,00%",0,0.0,0.0,0.0,...,0.0,"0,00%","0,00%",0,"0,00%","7,61%",000,9.145.920.00000,0.0,"-5,18%"
3,CFLU4,1.0,0.0,0.0,0.0,"0,00%",0,0.0,0.0,0.0,...,0.0,"8,88%","10,72%",110,"17,68%","32,15%",000,60.351.00000,6.0,"8,14%"
4,CLAN3,0.0,0.0,0.0,0.0,"0,00%",0,0.0,0.0,0.0,...,0.0,"0,00%","0,00%",0,"0,00%","-1,05%",000,1.012.240.00000,0.0,"-63,96%"

In [3]:
df.head(5)

,Papel,Cotação,P/L,P/VP,PSR,Div.Yield,P/Ativo,P/Cap.Giro,P/EBIT,P/Ativ Circ.Liq,...,EV/EBITDA,Mrg Ebit,Mrg. Líq.,Liq. Corr.,ROIC,ROE,Liq.2meses,Patrim. Líq,Dív.Brut/ Patrim.,Cresc. Rec.5a
0,VSPT4,0.0,0.0,0.0,0.0,"0,00%",0,0.0,0.0,0.0,...,0.0,"0,00%","0,00%",0,"0,00%","-2,62%",000,4.736.050.00000,0.0,"438,95%"
1,VSPT3,0.0,0.0,0.0,0.0,"0,00%",0,0.0,0.0,0.0,...,0.0,"0,00%","0,00%",0,"0,00%","-2,62%",000,4.736.050.00000,0.0,"438,95%"
2,VNET3,0.0,0.0,0.0,0.0,"0,00%",0,0.0,0.0,0.0,...,0.0,"0,00%","0,00%",0,"0,00%","7,61%",000,9.145.920.00000,0.0,"-5,18%"
3,CFLU4,1.0,0.0,0.0,0.0,"0,00%",0,0.0,0.0,0.0,...,0.0,"8,88%","10,72%",110,"17,68%","32,15%",000,60.351.00000,6.0,"8,14%"
4,CLAN3,0.0,0.0,0.0,0.0,"0,00%",0,0.0,0.0,0.0,...,0.0,"0,00%","0,00%",0,"0,00%","-1,05%",000,1.012.240.00000,0.0,"-63,96%"

In [4]:
#type(lista)
#print(lista)

In [5]:
for coluna in ['Div.Yield', 'Mrg Ebit', 'Mrg. Líq.', 'ROIC', 'ROE', 'Cresc. Rec.5a','EV/EBIT']:
  df[coluna] = df[coluna].str.replace('.', '')
  df[coluna] = df[coluna].str.replace(',', '.')
  df[coluna] = df[coluna].str.rstrip('%').astype('float') / 100

# Analisando os dados

In [6]:
#engenhosidade, estava dando erro entao eu fiz a conversao logo abaixo
#df['Liq.2meses'] = pd.to_numeric(df['Liq.2meses'], errors='coerce')

#df = df[df['Liq.2meses'] > 1000000]
df.head()

,Papel,Cotação,P/L,P/VP,PSR,Div.Yield,P/Ativo,P/Cap.Giro,P/EBIT,P/Ativ Circ.Liq,...,EV/EBITDA,Mrg Ebit,Mrg. Líq.,Liq. Corr.,ROIC,ROE,Liq.2meses,Patrim. Líq,Dív.Brut/ Patrim.,Cresc. Rec.5a
0,VSPT4,0.0,0.0,0.0,0.0,0.0,0,0.0,0.0,0.0,...,0.0,0.0000,0.0000,0,0.0000,-0.0262,000,4.736.050.00000,0.0,4.3895
1,VSPT3,0.0,0.0,0.0,0.0,0.0,0,0.0,0.0,0.0,...,0.0,0.0000,0.0000,0,0.0000,-0.0262,000,4.736.050.00000,0.0,4.3895
2,VNET3,0.0,0.0,0.0,0.0,0.0,0,0.0,0.0,0.0,...,0.0,0.0000,0.0000,0,0.0000,0.0761,000,9.145.920.00000,0.0,-0.0518
3,CFLU4,1.0,0.0,0.0,0.0,0.0,0,0.0,0.0,0.0,...,0.0,0.0888,0.1072,110,0.1768,0.3215,000,60.351.00000,6.0,0.0814
4,CLAN3,0.0,0.0,0.0,0.0,0.0,0,0.0,0.0,0.0,...,0.0,0.0000,0.0000,0,0.0000,-0.0105,000,1.012.240.00000,0.0,-0.6396

In [7]:
# Vamos tentar converter pra não dar erro nos campos da proxima célula
#for coluna in [ 'EV/EBIT',  'ROIC']:
#  df[coluna] = df[coluna].str.replace('.', '')
#  df[coluna] = df[coluna].astype('float')

In [8]:

ranking = pd.DataFrame()
ranking['pos'] = range(1,151)
ranking['EV/EBIT'] = df[ df['EV/EBIT'] > 0 ].sort_values(by=['EV/EBIT'])['Papel'][:150].values
ranking['ROIC'] = df.sort_values(by=['ROIC'], ascending=False)['Papel'][:150].values

In [9]:
ranking

     pos EV/EBIT    ROIC
0      1   TPRC3   OMGE3
1      2   CMMA4   TRPN3
2      3   PSSA3   ADHM3
3      4   MSAN4   VTLM3
4      5   MSAN3   BPHA3
5      6   BELG4   MPLU3
6      7   BELG3   AZEV3
7      8   CORR4   AZEV4
8      9   FIGE4  AGEN33
9     10   MNPR4   CMET4
10    11  GPIV33   WIZS3
11    12   LREN4   PSSA3
12    13   ILLS4   ATOM3
13    14   MNPR3   CPSL3
14    15   JBDU4   DSUL3
15    16   SMLS3   CRUZ3
16    17   MTBR3   SMLE3
17    18   GAZO4   ODPV3
18    19   SALM4   AVIL3
19    20   SALM3   GALO4
20    21   MTBR4   GALO3
21    22   DSUL3   BCAL6
22    23   LATS3   PMET6
23    24   TSPP4   PMET5
24    25   SULA4   ASSM3
25    26   FIGE3   ASSM4
26    27   JBDU3   TEMP3
27    28   GAZO3   AMBV4
28    29   CSPC4   AMBV3
29    30   CSPC3   AFLU5
..   ...     ...     ...
120  121   ACES4   TBLE5
121  122   ACES3   ESCE3
122  123   PEFX3  TEFC11
123  124   PEFX5   ABEV3
124  125   CSMG3   DURA4
125  126   VIVO3   DURA3
126  127   BOBR4   EQPA3
127  128   VGOR3   EQPA7
128  129   ENBR3   EQPA5
129  130   BEEF3   EQPA6
130  131   ALUP3   PALF5
131  132   EEEL4   PALF3
132  133   BMKS3  PALF11
133  134   EQPA3   B3SA3
134  135   PTPA3   MAGG3
135  136   SCAR4   TCOC3
136  137   CLSC4   TCOC4
137  138   FIBR3   CARD3
138  139   MNDL3   EKTR4
139  140   ELET5   EKTR3
140  141   VIVO4   VIVA3
141  142   TRPL3  WSON33
142  143   PTPA4   AFLT3
143  144   EKTR4   MGEL3
144  145   AFLU5   MGEL4
145  146   CRPG5   BRTP3
146  147   VINE3   BRTP4
147  148  WSON33   EEEL4
148  149   CIQU4   EEEL3
149  150   CIQU3   TRPL3

[150 rows x 3 columns]

In [10]:
a = ranking.pivot_table(columns='EV/EBIT', values='pos')

In [11]:
b = ranking.pivot_table(columns='ROIC', values='pos')

In [12]:
t = pd.concat([a,b])
t

,ABEV3,ACES3,ACES4,ADHM3,AFLT3,AFLU3,AFLU5,AGEN33,ALBA3,ALUP11,...,VIVA3,VIVO3,VIVO4,VTLM3,WEGE3,WEGE4,WHRL3,WHRL4,WIZS3,WSON33
pos,NaN,122,121,NaN,NaN,NaN,145,69,NaN,114.0,...,NaN,126,141,NaN,NaN,NaN,NaN,NaN,65,148
pos,124.0,42,41,3.0,143.0,31.0,30,9,81.0,NaN,...,141.0,56,58,4.0,93.0,92.0,87.0,86.0,11,142

In [13]:
rank = t.dropna(axis=1).sum()
rank

ACES3     164
ACES4     162
AFLU5     175
AGEN33     78
AMPI3     120
ASSM3      66
ASSM4      66
AZEV3      63
AZEV4      47
BEEF3     214
BELG3      80
BELG4      81
BOBR3     154
BOBR4     203
BPHA3      41
BRTP4     234
BTTL4     170
CMET4     102
CPSL3     110
CSPC3      64
CSPC4      62
DSUL3      37
EEEL3     255
EEEL4     280
EKTR4     283
ENER3     167
ENER5     167
ENER6     167
EQPA3     261
EQTL3     231
         ...
MRFG3     111
MTBR3     102
MTBR4     109
PALF11    185
PALF3     187
PALF5     185
PSSA3      15
PTIP3     129
PTIP4     131
SALM3      65
SALM4      63
SAPR11    197
SAPR3     203
SAPR4     198
SMLS3      56
TBLE5     216
TBLE6     210
TEFC11    187
TRFO3     127
TRFO4     128
TRPL3     292
TSPP3      92
TSPP4      81
VALE3     199
VALE5     164
VCPA4     135
VIVO3     182
VIVO4     199
WIZS3      76
WSON33    290
Length: 69, dtype: int64

In [14]:
rank.sort_values()[:15]

PSSA3    15
DSUL3    37
BPHA3    41
AZEV4    47
SMLS3    56
CSPC4    62
SALM4    63
AZEV3    63
CSPC3    64
GAZO4    65
SALM3    65
ASSM3    66
ASSM4    66
MNPR4    71
MNPR3    74
dtype: int64